spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/IHTAR
      client:
        registration:
          keycloak:
            client-id: schedule-app-be
            client-secret: 7a280692-2c98-40a0-8046-66e6d5d54bcb
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/auth/realms/IHTAR

  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      default-filters:
        - TokenRelay
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            redis-rate-limiter.requestedTokens: 1
      routes:
        - id: meeting-route
          uri: lb://meeting-manager-service
          predicates:
            - Path=/meetings/**
            - Path=/meeting-provider/**
          filters:
#            - name: CircuitBreaker
#              args:
#                name: meeting-manager-service
#                fallbackUri: forward:/meeting-manager-fallback
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms

resilience4j:
  circuitbreaker:
    instances:
      meetingService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true
  timelimiter:
    instances:
      meeting-manager-service:
        timeoutDuration: 2s
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    preferIpAddress: true
